// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anpxlozgvhjrfmvbkics.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFucHhsb3pndmhqcmZtdmJraWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NzUwOTgsImV4cCI6MjA1MDE1MTA5OH0.EDTah_he0y7as9tttMFZNs9_-6WUhH2DGOaF6KfmCf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);