// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnxnlryoewwpjxxdkmty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFueG5scnlvZXd3cGp4eGRrbXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MjM5MDQsImV4cCI6MjA1MDE5OTkwNH0.NkQxWPIIAh1IXeSj_F7IzzRxPYz61k7DEm0XoCqUqp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);